name: Main
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Action
        id: hello
        uses: wxdlong/hello-action@v7
        with:
          who-to-greet: Jason
      - name: Show time
        run: echo "Time is ${{ steps.hello.outputs.time }}"
      - name: Test action
        uses: ./.github/actions/test-action